### ISSUE TITLE
triplet loss请教下

### ISSUE THREAD

**Issue by hgzry2015** [xuqiantong/MyCaffe#1]
你好打扰了，triplet loss 里面打代码，函数CLLBackward()里面，
int n = i / channels; 这一行是为什么？这里的i是线程索引，总共线程是count(batchsize大小)，每个线程i可以处理一个样本的特征（channel大小），为什么还要除以channel呢？

这里除以channel是什么意思呢？

谢谢大神，打扰了，我跑过triplet loss代码，今天细看代码时发现了这个问题没明白。

**Comment by xuqiantong** [comment]
你好，

当时这个triplet
loss的code我是偷懒从网上粘来的，我大致看了一下是对的，就没仔细研究。但你的问题很有意思，我帮你琢磨了一下。我觉得问题主要在CUDA_KERNEL_LOOP
函数。参考
http://caffe.berkeleyvision.org/doxygen/device__alternate_8hpp_source.html，
因为i += blockDim.x *
gridDim.x，我猜blockDim.x或者gridDim.x里面一个是样本总数(batchsize大小)，一个是每个样本的channel数。count这个变量本身是输入batch的总的参数个数，所以CUDA_KERNEL_LOOP可能就是，cuda并行了样本（三维tensor）的每一个pixel，然后for
loop来找下一个样本对应位置的pixel在哪，i是pixel的位置。所以 i / channels（这里取整了）才是对应的样本的index。

以上纯属猜测，你可以顺着这个思路看看，有问题的话可以再讨论。

2018-01-09 11:55 GMT+08:00 ryzhang <notifications@github.com>:

**Comment by hgzry2015** [comment]
谢谢你的回复，谢谢你重新看这个代码。
我昨天大概清楚了这个原因。你的解释是正确的。谢谢。







在 2018-01-10 10:32:54，"Qiantong" <notifications@github.com> 写道：
你好，

当时这个triplet
loss的code我是偷懒从网上粘来的，我大致看了一下是对的，就没仔细研究。但你的问题很有意思，我帮你琢磨了一下。我觉得问题主要在CUDA_KERNEL_LOOP
函数。参考
http://caffe.berkeleyvision.org/doxygen/device__alternate_8hpp_source.html，
因为i += blockDim.x *
gridDim.x，我猜blockDim.x或者gridDim.x里面一个是样本总数(batchsize大小)，一个是每个样本的channel数。count这个变量本身是输入batch的总的参数个数，所以CUDA_KERNEL_LOOP可能就是，cuda并行了样本（三维tensor）的每一个pixel，然后for
loop来找下一个样本对应位置的pixel在哪，i是pixel的位置。所以 i / channels（这里取整了）才是对应的样本的index。

以上纯属猜测，你可以顺着这个思路看看，有问题的话可以再讨论。

2018-01-09 11:55 GMT+08:00 ryzhang <notifications@github.com>:
